---
# handlers file for ansible-role-janus-gateway

- name: reindex shared libraries
  become: true
  ansible.builtin.command:
    cmd: ldconfig

- name: restart janus service
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    name: janus
    state: restarted