---
# handlers file for ansible-role-janus-gateway

- name: reindex shared libraries
  become: true
  # Deliberately don't use the FQDN ansible.builtin.command because it doesn't
  # work with Ansible 2.x: https://github.com/ansible/ansible/issues/71817
  command: ldconfig

- name: restart janus service
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
    name: janus
    state: restarted